---
- name: be sure ntp is installed
  yum:
    name: chrony
    state: present
  tags: ntp
- name: be sure ntp is configured
  template:
    src: chrony.conf
    dest: /etc/chrony.conf
  notify:
    - restart ntpd
  tags: ntp
- name: be sure ntpd is running and enabled
  service:
    name: chronyd
    state: started
    enabled: yes
  tags: ntp
- name: Set Timezone
  community.general.timezone:
   name: Africa/Cairo
